spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    schema: classpath:/static/schema.sql
  h2:
    console:
      enabled: true
jwt:
  token:
    secret: testObj
    expired: 3600000

fixer-url: http://data.fixer.io/api/latest?access_key=25fd33197a3b30bd176c0c6b809c466a

